spring:
  application:
    name: kb-tool-service
  profiles:
    active: dev
  jpa:
    open-in-view: false

  datasource:
    max-active: 15
    max-idle: 10
    max-wait: 8000

server:
  port: 8080
